version: "3"

services:
  jenkins:
    build:
      context: jenkins
    ports:
      - 8084:8080
      - 50000:50000
    volumes:
          - "jenkins-data:/var/jenkins_home"

volumes:
  jenkins-data:
